# Generated by Django 5.1.3 on 2026-09-02 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositdeduction',
            options={'ordering': ['-deduction_date']},
        ),
        migrations.AlterModelOptions(
            name='depositrefund',
            options={'ordering': ['-refund_date']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-request_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='securitydeposit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='depositdeduction',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_deductions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='depositrefund',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('electricity', 'Electricity'), ('water', 'Water'), ('cleaning', 'Cleaning'), ('insurance', 'Insurance'), ('repairs', 'Repairs'), ('management', 'Management'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('recorded', 'Recorded'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='recorded', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
